# Generated by Django 3.0.6 on 2020-06-17 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('slug', models.SlugField()),
                ('nav_type', models.CharField(choices=[('n', 'none'), ('t', 'top level'), ('s', 'sub level'), ('f', 'footer')], default='n', max_length=1, verbose_name='navigation type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('slug', models.SlugField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='is visible')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('author', models.DateField()),
                ('published_on', models.DateTimeField(blank=True, null=True, verbose_name='published on')),
                ('page_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='pages.PageType', verbose_name='page type')),
                ('tags', models.ManyToManyField(related_name='pages', to='pages.Tag', verbose_name='page type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
