name: Branch Version

on:
  push:
    branches-ignore: [latest]

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check branch version
        uses: pharingee/branch-version-action@v1.5
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          versionFile: VERSION
